name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Replace with yarn if you use yarn

      - name: Build
        run: npm run build  # Replace with yarn build if you use yarn

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Path to your build directory

